# Generated by Django 4.2.2 on 2023-07-04 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_task_audithistory_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(
                blank=True, related_name='project_assign',
                to=settings.AUTH_USER_MODEL
                ),
        ),
        migrations.AlterField(
            model_name='project',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
