# Generated by Django 4.2.2 on 2023-06-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('password',
                 models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login'
                    )),
                ('username', models.CharField(
                    default='user', max_length=20, unique=True,
                    verbose_name='Username'
                    )),
                ('firstname',
                 models.CharField(blank=True, max_length=20, null=True)),
                ('lastname',
                 models.CharField(blank=True, max_length=20, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('contact_no', phone_field.models.PhoneField(
                    blank=True, max_length=31, null=True
                    )),
                ('email', models.EmailField(
                    max_length=254, unique=True, verbose_name='Email Address'
                    )),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='active')),
                ('is_superuser',
                 models.BooleanField(default=False, verbose_name='superuser')),
                ('is_staff',
                 models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(
                    default='profiles/default.png', upload_to='profiles/'
                    )),
                ('is_owner', models.BooleanField(default=False)),
                ('has_changed_password', models.BooleanField(default=False)),
                ('stripe_customer_id',
                 models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id',
                 models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', phone_field.models.PhoneField(
                    blank=True, max_length=31, null=True
                    )),
                ('website', models.URLField(blank=True, null=True)),
                ('subscription_end_date',
                 models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status',
                 models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_id',
                 models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='authentication.company'
                    )),
                ('transaction_made_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                    )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='authentication.company'
                ),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                related_name='user_set', related_query_name='user',
                to='auth.group', verbose_name='groups'
                ),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(
                blank=True, help_text='Specific permissions for this user.',
                related_name='user_set', related_query_name='user',
                to='auth.permission', verbose_name='user permissions'
                ),
        ),
    ]
