# Generated by Django 4.2.2 on 2023-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
